
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author laptop ko
 */
public class Carpanel extends javax.swing.JPanel {

    /**
     * Creates new form carpane
     */
    public Carpanel() {
        initComponents();
        refreshcartable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addvehicle = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        vmodel = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        vplateno = new javax.swing.JTextField();
        vyearmodel = new com.toedter.calendar.JYearChooser();
        vtype = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        vbrand = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        vcolortext = new javax.swing.JTextField();
        vcolorcombo = new javax.swing.JComboBox<>();
        carsave = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        carsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        cartable = new javax.swing.JTable();

        addvehicle.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addvehicle.setMinimumSize(new java.awt.Dimension(693, 470));
        addvehicle.setModal(true);

        jLabel35.setBackground(new java.awt.Color(153, 153, 153));
        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setText("Vehicle Type");

        vmodel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vmodel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        vmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vmodelActionPerformed(evt);
            }
        });

        jLabel41.setBackground(new java.awt.Color(153, 153, 153));
        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel41.setText("Model");

        jLabel37.setBackground(new java.awt.Color(153, 153, 153));
        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel37.setText("Color");

        vplateno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vplateno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        vyearmodel.setValue(2000);

        vtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select here", "Car", "Bus" }));

        jLabel40.setBackground(new java.awt.Color(153, 153, 153));
        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel40.setText("Brand");

        vbrand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vbrand.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel38.setBackground(new java.awt.Color(153, 153, 153));
        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel38.setText("Plate number");

        jLabel42.setBackground(new java.awt.Color(153, 153, 153));
        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel42.setText("Year Model");

        vcolortext.setEditable(false);
        vcolortext.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vcolortext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        vcolortext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vcolortextMouseClicked(evt);
            }
        });
        vcolortext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vcolortextKeyReleased(evt);
            }
        });

        vcolorcombo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vcolorcombo.setMaximumRowCount(1000);
        vcolorcombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vcolorcomboItemStateChanged(evt);
            }
        });
        vcolorcombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vcolorcomboMouseClicked(evt);
            }
        });
        vcolorcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcolorcomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vmodel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vplateno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vcolorcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vcolortext))
                            .addComponent(vtype, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vyearmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel35, jLabel37, jLabel38, jLabel40, jLabel41, jLabel42});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {vbrand, vmodel, vplateno, vtype, vyearmodel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(vtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(vcolorcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vcolortext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(vplateno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(vbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(vmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42)
                    .addComponent(vyearmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel35, jLabel37, jLabel38, jLabel40, jLabel41, jLabel42, vbrand, vcolorcombo, vcolortext, vmodel, vplateno, vtype, vyearmodel});

        carsave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        carsave.setForeground(new java.awt.Color(0, 204, 0));
        carsave.setText("Save");
        carsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carsaveActionPerformed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(153, 153, 153));
        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("FILL UP FORM");
        jLabel25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout addvehicleLayout = new javax.swing.GroupLayout(addvehicle.getContentPane());
        addvehicle.getContentPane().setLayout(addvehicleLayout);
        addvehicleLayout.setHorizontalGroup(
            addvehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addvehicleLayout.createSequentialGroup()
                .addGroup(addvehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addvehicleLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addvehicleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addvehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(addvehicleLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(carsave, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        addvehicleLayout.setVerticalGroup(
            addvehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addvehicleLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carsave)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        carsearch.setBackground(new java.awt.Color(204, 204, 204));
        carsearch.setToolTipText("type to search");
        carsearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        carsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carsearchActionPerformed(evt);
            }
        });
        carsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carsearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Search");

        jButton4.setText("ADD VEHICLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vehicle's table");

        cartable.setBackground(new java.awt.Color(204, 204, 255));
        cartable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle Name", "Plate Number", "Type", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartable.setToolTipText("click the row to edit or delete");
        cartable.setGridColor(new java.awt.Color(153, 255, 153));
        cartable.setIntercellSpacing(new java.awt.Dimension(1, 2));
        cartable.setSelectionBackground(new java.awt.Color(0, 84, 215));
        cartable.setSelectionForeground(new java.awt.Color(204, 204, 0));
        cartable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(cartable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carsearch)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {delete, jButton4, jLabel2, update});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(23, 23, 23))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {delete, jButton4, update});

    }// </editor-fold>//GEN-END:initComponents

    private void cartableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartableMouseClicked
        update.setEnabled(true);
        delete.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cartableMouseClicked

    private void vcolorcomboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vcolorcomboMouseClicked
        if (vcolorcombo.getSelectedIndex() == 0) {
            vcolortext.setEditable(true);
        } else {
            vcolortext.setEditable(false);
            // vcolortext.setText(vcolorcombo.getSelectedItem().toString());

        }// TODO add your handling code here:
    }//GEN-LAST:event_vcolorcomboMouseClicked

    private void vcolortextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vcolortextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vcolortextMouseClicked

    private void vmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vmodelActionPerformed

    private void carsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carsaveActionPerformed
        if (vtype.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select vehicle type", "Message", JOptionPane.WARNING_MESSAGE);
        } else if (vcolorcombo.getSelectedIndex() == 0 || vcolorcombo.getSelectedIndex() == vcolorcombo.getItemCount() - 1 && vcolortext.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select or type the color of the vehicle", "Message", JOptionPane.WARNING_MESSAGE);
        } else if (vplateno.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up the plate number", "Message", JOptionPane.WARNING_MESSAGE);
        } else if (vbrand.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up the brand", "Message", JOptionPane.WARNING_MESSAGE);
        } else if (vmodel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill up the model", "Message", JOptionPane.WARNING_MESSAGE);
//        } else if (vyearmodel.getYear() == 2000) {
//            int x = JOptionPane.showConfirmDialog(null, "2000 is the year model?", "Message", JOptionPane.YES_NO_OPTION, 3);
//            if (x == JOptionPane.NO_OPTION) {
//                JOptionPane.showMessageDialog(null, "Please fill up or select the year model", "Message", JOptionPane.WARNING_MESSAGE);
        } else if (vcolortext.getForeground() == Color.RED) {
            JOptionPane.showMessageDialog(null, "The color you typed is in the combo box. Please find it and click it", "Message", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(new connect().database_url);

                if ("UPDATE".equals(carsave.getText())) {
                    int row = cartable.getSelectedRow();
                    TableModel model = cartable.getModel();
                    String l = model.getValueAt(row, 1).toString();
                    PreparedStatement pstmt = con.prepareStatement("UPDATE vehicle set v_type = ?,color=?,plate_no=?,"
                            + "brand=?,model=?,yearmodel=? WHERE plate_no = '" + l + "';");
                    pstmt.setString(1, vtype.getSelectedItem().toString());
                    if (vcolortext.getText().isEmpty()) {
                        pstmt.setString(2, vcolorcombo.getSelectedItem().toString());
                    } else {
                        pstmt.setString(2, vcolortext.getText());
                    }
                    pstmt.setString(3, vplateno.getText());
                    pstmt.setString(4, vbrand.getText());
                    pstmt.setString(5, vmodel.getText());
                    pstmt.setString(6, vyearmodel.getYear() + "");
                    pstmt.execute();

                    JOptionPane.showMessageDialog(null, "Successfully Updated");
                    if (vcolortext.getText().isEmpty()) {
                    } else {
                        PreparedStatement pstmt1 = con.prepareStatement("INSERT INTO vehiclecolor values (null,?);");
                        pstmt1.setString(1, vcolortext.getText());
                        pstmt1.execute();
                    }
                    this.addvehicle.dispose();
                } else {

                    PreparedStatement pstmt = con.prepareStatement("INSERT INTO vehicle VALUES (null,?,?,?,?,?,?);");
                    pstmt.setString(1, vtype.getSelectedItem().toString());
                    if (vcolortext.getText().isEmpty()) {
                        pstmt.setString(2, vcolorcombo.getSelectedItem().toString());
                    } else {
                        pstmt.setString(2, vcolortext.getText());
                    }
                    pstmt.setString(3, vplateno.getText());
                    pstmt.setString(4, vbrand.getText());
                    pstmt.setString(5, vmodel.getText());
                    pstmt.setString(6, vyearmodel.getYear() + "");
                    pstmt.execute();

                    JOptionPane.showMessageDialog(null, "Successfully save");
                    if (vcolortext.getText().isEmpty()) {
                    } else {
                        PreparedStatement pstmt1 = con.prepareStatement("INSERT INTO vehiclecolor values (null,?);");
                        pstmt1.setString(1, vcolortext.getText());
                        pstmt1.execute();
                    }
                }
                vtype.setSelectedIndex(0);

                vcolortext.setText("");
                vplateno.setText("");
                vbrand.setText("");
                vmodel.setText("");
                vyearmodel.setYear(2000);

                coloradd();
                refreshcartable();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Carpanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            // }
        }
    }//GEN-LAST:event_carsaveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        coloradd();
        addvehicle.setLocationRelativeTo(null);
        addvehicle.setVisible(true);
        vcolortext.setEditable(false);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void vcolorcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcolorcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcolorcomboActionPerformed

    private void vcolorcomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vcolorcomboItemStateChanged
        if (vcolorcombo.getSelectedIndex() + 1 == vcolorcombo.getItemCount() || vcolorcombo.getSelectedIndex() == 0) {
            vcolortext.setVisible(true);
            vcolortext.setEditable(true);
        } else {
            vcolortext.setVisible(false);
            vcolortext.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_vcolorcomboItemStateChanged

    private void vcolortextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcolortextKeyReleased
        vcolorcombo.setSelectedIndex(vcolorcombo.getItemCount() - 1);

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(new connect().database_url);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM vehiclecolor WHERE colorname = '" + vcolortext.getText() + "';");
            if (rs.next()) {
                vcolortext.setForeground(Color.red);
            } else {
                vcolortext.setForeground(Color.BLACK);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Carpanel.class.getName()).log(Level.SEVERE, null, ex);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_vcolortextKeyReleased

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if (cartable.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one(1)", "Message", 0);
        } else {
            int row = cartable.getSelectedRow();
            TableModel model = cartable.getModel();
            String l = model.getValueAt(row, 1).toString();
            coloradd();

            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(new connect().database_url);
                Statement smt = con.createStatement();
                ResultSet rs = smt.executeQuery("SELECT * FROM vehicle WHERE plate_no = '" + l + "';");

                if (rs.first()) {
                    vtype.setSelectedItem(rs.getString("v_type"));
                    vcolortext.setVisible(true);
                    vcolorcombo.setSelectedItem(rs.getString("color"));
                    vplateno.setText(rs.getString("plate_no"));
                    vbrand.setText(rs.getString("brand"));
                    vmodel.setText(rs.getString("model"));
                    vyearmodel.setYear(rs.getInt("yearmodel"));

                    carsave.setText("UPDATE");
                    addvehicle.setLocationRelativeTo(null);
                    addvehicle.setVisible(true);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Driverpanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void carsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carsearchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int rowcount = cartable.getSelectedRowCount();
        int[] rows = cartable.getSelectedRows();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(new connect().database_url);
            Statement smt = con.createStatement();
            int x = JOptionPane.showConfirmDialog(null, "Delete the selected " + rowcount + " row(s)?", "Warning", JOptionPane.YES_NO_OPTION, 2);
            if (x == JOptionPane.YES_OPTION) {
                while (rowcount > 0) {
                    TableModel model = cartable.getModel();
                    String l = model.getValueAt(rows[rowcount - 1], 1).toString();
                    String sql = "DELETE FROM vehicle WHERE plate_no = '" + l + "';";
                    smt.execute(sql);
                    rowcount--;
                }
            }
            refreshcartable();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Driverpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void carsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carsearchKeyReleased
        String pangita = carsearch.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(new connect().database_url);
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM vehicle WHERE 1=1 ";

            if (pangita != (null)) {
                sql = sql + "and (v_type like '%" + pangita + "%'"
                        + " or brand like '%" + pangita + "%'"
                        + " or model like '%" + pangita + "%'"
                        + " or yearmodel like '%" + pangita + "%');";
            }
            ResultSet rs = stmt.executeQuery(sql);
            DefaultTableModel studentsModel = new connect().ct;
            int row = 0;
            while (rs.next()) {
                studentsModel.addRow(new Object[]{});
                studentsModel.setValueAt(rs.getString("brand") + " " + rs.getString("model") + " (" + rs.getInt("yearmodel") + ")", row, 0);
                studentsModel.setValueAt(rs.getString("plate_no"), row, 1);
                studentsModel.setValueAt(rs.getString("v_type"), row, 2);
                studentsModel.setValueAt(rs.getString("color"), row, 3);
                row++;
            }
            cartable.setModel(studentsModel);

            update.setEnabled(false);
            delete.setEnabled(false);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Carpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_carsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addvehicle;
    private javax.swing.JButton carsave;
    private javax.swing.JTextField carsearch;
    private javax.swing.JTable cartable;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton update;
    private javax.swing.JTextField vbrand;
    private javax.swing.JComboBox<String> vcolorcombo;
    private javax.swing.JTextField vcolortext;
    private javax.swing.JTextField vmodel;
    private javax.swing.JTextField vplateno;
    private javax.swing.JComboBox<String> vtype;
    private com.toedter.calendar.JYearChooser vyearmodel;
    // End of variables declaration//GEN-END:variables
private void coloradd() {
        vcolorcombo.removeAllItems();
        vcolorcombo.addItem("Select here");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(new connect().database_url);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM vehiclecolor ORDER BY colorname;");

            while (rs.next()) {
                String color = rs.getString("colorname");
                vcolorcombo.addItem(color);
            }
            vcolorcombo.addItem("add color");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Carpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }

    private void refreshcartable() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(new connect().database_url);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM vehicle;");
            DefaultTableModel studentsModel = new connect().ct;
            int row = 0;
            while (rs.next()) {
                studentsModel.addRow(new Object[]{});
                studentsModel.setValueAt(rs.getString("brand") + " " + rs.getString("model") + " (" + rs.getInt("yearmodel") + ")", row, 0);
                studentsModel.setValueAt(rs.getString("plate_no"), row, 1);
                studentsModel.setValueAt(rs.getString("v_type"), row, 2);
                studentsModel.setValueAt(rs.getString("color"), row, 3);
                row++;
            }
            cartable.setModel(studentsModel);

            update.setEnabled(false);
            delete.setEnabled(false);

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Carpanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
